server:
 port: 7062
spring:
  profiles:
    active: dev
  application:
   name: configserver
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/oilqw/mall/
          searchPaths: mall-core/config
          username: oilqw
          password: Pass1234
          clone-on-start: true
security:
  user:
    name: admin
    password: admin123
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
  client:
    service-url:
      defaultZone: http://ouwenjie.com:7061/eureka
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
    
    
