server:
 port: 8080
spring:
  profiles:
    active: dev
  application:
   name: config_server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/oilqw/mall/
          searchPaths: mall-core/config
          username: oilqw
          password: Pass1234
security:
  user:
    name: admin
    password: admin123
eureka:
  client:
    service-url:
      defaultZone: http://ouwenjie.com:7061/eureka/