server:
  port: 7061
spring:
  application:
    name: eureka_server
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: ouwenjie.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka