server:
  port: 8080
spring:
  application:
    name: eureka_server 
eureka:
  instance:
    hostname: ouwenjie.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/