server:
  port: 8080
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:7061/eureka
spring:
  application:
    name: UUMS-SERVER
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.199.184:6072/test?useUnicode=true&characterEncoding=utf8
     username: root
     password: admin123
     initialSize: 1
     minIdle: 1
     maxActive: 20
     maxWait: 60000
     validationQuery: SELECT 1 FROM DUAL
     testOnBorrow: false
     testOnReturn: false
     testWhileIdle: true
     minEvictableIdleTimeMillis: 25200000
     timeBetweenEvictionRunsMillis: 60000
     removeAbandoned: true
     removeAbandonedTimeout: 1800
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     logAbandoned: true
     filters: stat,wall,log4j
     druid:
        web-stat-filter:
          session-stat-enable: true
          session-stat-max-count: 100000
          profile-enable: true
          enabled: true
          url-pattern: /*
          exclusions: >
            *.js,
            *.gif,
            *.jpg,
            *.bmp,
            *.png,
            *.css,
            *.ico,
            /druid/*
        stat-view-servlet:
            enabled: true
            login-username: admin
            login-password: admin123
            url-pattern: /druid/*
            reset-enable: true
            allow: 192.168.1.72,127.0.0.1
            deny: 192.168.1.73
        filter:
          wall:
            enabled: true
            db-type: mysql
            config:
              alter-table-allow: false
              truncate-allow: false
              drop-table-allow: false
              none-base-statement-allow: false
              update-where-none-check: true
              select-into-outfile-allow: false
              metadata-allow: true
            log-violation: true
            throw-exception: true
          slf4j:
            enabled: true
            connection-log-enabled: true
            connection-close-after-log-enabled: true
            connection-commit-after-log-enabled: true
            connection-connect-after-log-enabled: true
            connection-connect-before-log-enabled: true
            connection-log-error-enabled: true
            data-source-log-enabled: true
            result-set-log-enabled: true
            statement-log-enabled: true
  jpa:
    database: MYSQL
    show-sql: true