eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-zuul
zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: admin-web
    api-b:
      path: /api-b/**
      serviceId: service-feign